# Generated by Django 4.1.2 on 2022-11-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Movie',
        ),
    ]
